### ISSUE TITLE
503 Service Unavailable when installing

### ISSUE THREAD

**Issue by ellenchristine** [braintree/credit-card-type#87]
Every time I try to install this package I get the following:

`503 Service Unavailable: credit-card-type@7.0.0`

This occurs no matter what version I target. I first noticed the issue when trying to install the card-validator package, with this as a dependency. I tried installing credit-card-type directly with the same error.

I'm able to install other Node packages with no issues.

Here are the verbose logs:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'credit-card-type@6.0.0' ]
2 info using npm@6.5.0
3 info using node@v8.10.0
4 verbose npm-session 2cabcfb8b331a09b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/credit-card-type 17ms (from cache)
8 http fetch GET 503 https://registry.npmjs.org/credit-card-type/-/credit-card-type-6.0.0.tgz 71377ms attempt #3
9 silly fetchPackageMetaData error for credit-card-type@6.0.0 503 Service Unavailable: credit-card-type@6.0.0
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 71635ms
12 verbose stack Error: 503 Service Unavailable: credit-card-type@6.0.0
12 verbose stack     at fetch.then.res (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
12 verbose stack     at tryCatcher (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
12 verbose stack     at Promise._settlePromise (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
12 verbose stack     at Promise._settlePromises (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
12 verbose stack     at _drainQueueStep (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
12 verbose stack     at _drainQueue (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
12 verbose stack     at Async._drainQueues (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues (/Users/e034162/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at runCallback (timers.js:794:20)
12 verbose stack     at tryOnImmediate (timers.js:752:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
13 verbose cwd /Users/e034162/projects/srci
14 verbose Darwin 16.7.0
15 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "credit-card-type@6.0.0"
16 verbose node v8.10.0
17 verbose npm  v6.5.0
18 error code E503
19 error 503 Service Unavailable: credit-card-type@6.0.0
20 verbose exit [ 1, true ]

```

**Comment by crookedneighbor** [comment]
This looks like an issue with the npm registry, not the package. I was able to install it without issue:

```
$ npm i credit-card-type
/private/tmp
└── credit-card-type@8.1.0

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

$ npm i credit-card-type@7.0.0
/private/tmp
└── credit-card-type@7.0.0

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

$ npm i credit-card-type@6.0.0
/private/tmp
└── credit-card-type@6.0.0

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

$ node -v
v6.16.0

$ nvm use 8
Now using node v8.15.0 (npm v6.4.1)

$ npm i credit-card-type@6.0.0
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ credit-card-type@6.0.0
updated 1 package and audited 1 package in 2.588s
found 0 vulnerabilities
```
